
# Lista de Frases aleatórias para o Bot utilizar.

lista = ["Salada de Batata","Bora Bed?","Android VS Dinossauro","SUS","A Maçaneta da minha Kombi Quebrou","Feijão Voador","SHARK!","Anatidaefobia","Culto ao Pato","Ademiro me deu um tiro","Teletubies","SPY?","Tu é surdo?","Tu é cego?","O MACACO VAI CAIR",
"00:00, Horario oficial do Óleo de Macaco!","Meia Noite, Horario oficial do Óleo de Macaco","Edinaldo Pereira","Cheiro de Pneu Queimado","Carburador Furado","O X9 foi torrado","Alec Fake esteve aqui","Cabeça de Martelo","Todos os meninos com seus tenis boitos",
"AMOGUS","Azideia do Aleg","Imagens de Qualidade?","Sim, eu sou um Bot","Tucunaré Albino","É o Escrevas?","Tatu","Gameplay Quando?","Saudade dos velhos tempos...","Watchplay Quando?","Minezin Quando?","Malditos Comunas!","Como que funciona isso?",
"Como que faz isso?","Cogumelos Azuis","Rock da Mongolia","Esse Servidor ta mais parado que tudo","F","F Server","F Gameplays","AJUDA O MACACO","?","??","???","É o Digitas?","Se o pato perde a pata, ele fica manco ou viuvo?","PROTESTO!","Um momento!",
"OBJECTION","Ta pegando fogo bicho!","Falando de Ovo, eu gosto é de cozido","Inspetor Faustão","Hardcore","Aquela palavra com H...","Uno de Firma","Pastelão","Sabedoria Desbalanceada","Era uma vez os 3 porquinos...","Nada","Será que eu compro a goiaba?",
"Você é a vergonha da profissão!","Desliga o Freezer a Noite?","Estou sentindo uma Treta!","Não sei Rick, parece falso","Banido, Desbanido","Você não vale nada, Você vale Tudo!","Felipe Simith","Quero Café!","Eu fui programado...","Turip ip ip",
"Silencio, um usuario de Linux está criando uma pasta!","Windows ou Linux?","O Rock tem Guitarra, tem baixo e Bateria...","Não temo nenhum homem, mas aquela coisa... Aquilo me assusta","Oia a pedra","Yeah Yeah Yeah, piu piu","CAVALO!","Chuva?","Granizo?",
"Um guinomo estava andando em cima do asfalto...","I am the Storm that is Aproaching","Standing Here i Realize","Giga Chadd","Big Chungas","Redpilado","Dr. Livessey","Se você encara o Abismo, o Abismo te encara de volta..."]